"use client";

// ── Types ──────────────────────────────────────────────────────────────

export type AuditActionType =
  | "login"
  | "logout"
  | "create"
  | "update"
  | "delete"
  | "export"
  | "import"
  | "view"
  | "approve"
  | "reject";

export type AuditObjectType =
  | "application"
  | "client"
  | "partner"
  | "branch"
  | "user"
  | "settings";

export interface AuditChange {
  field: string;
  oldValue: string;
  newValue: string;
}

export interface AuditEntry {
  id: string;
  timestamp: Date;
  userId: string;
  userName: string;
  userRole: string;
  userAvatar?: string;
  ip: string;
  ipCity: string;
  ipCountry: string;
  userAgent: string;
  requestId: string;
  sessionId: string;
  actionType: AuditActionType;
  objectType: AuditObjectType;
  objectId: string;
  objectLabel: string;
  objectHref: string;
  changes: AuditChange[];
  oldJson?: Record<string, unknown>;
  newJson?: Record<string, unknown>;
  relatedEntryIds: string[];
}

export type SystemLogLevel = "error" | "warning" | "info" | "debug";

export interface SystemLogEntry {
  id: string;
  timestamp: Date;
  level: SystemLogLevel;
  component: string;
  message: string;
  stackTrace?: string;
}

export type IntegrationSource = "1c" | "bnpl" | "sms" | "email";
export type IntegrationDirection = "outgoing" | "incoming";

export interface IntegrationLogEntry {
  id: string;
  timestamp: Date;
  source: IntegrationSource;
  direction: IntegrationDirection;
  endpoint: string;
  statusCode: number;
  durationMs: number;
  retryCount: number;
  requestPayload: string;
  responsePayload: string;
}

export type SecurityAlertStatus = "active" | "resolved";

export interface SecurityAlert {
  id: string;
  timestamp: Date;
  severity: "critical" | "warning" | "info";
  title: string;
  description: string;
  status: SecurityAlertStatus;
  resolvedAt?: Date;
  resolvedBy?: string;
}

export interface AlertRule {
  id: string;
  trigger: string;
  threshold: number;
  unit: string;
  windowMinutes: number;
  recipients: string[];
  enabled: boolean;
}

// ── Styling helpers ────────────────────────────────────────────────────

export const ACTION_TYPE_STYLES: Record<
  AuditActionType,
  { label: string; className: string }
> = {
  login: {
    label: "Вход",
    className: "bg-blue-100 text-blue-800",
  },
  logout: {
    label: "Выход",
    className: "bg-gray-100 text-gray-800",
  },
  create: {
    label: "Создание",
    className: "bg-green-100 text-green-800",
  },
  update: {
    label: "Изменение",
    className: "bg-amber-100 text-amber-800",
  },
  delete: {
    label: "Удаление",
    className: "bg-red-100 text-red-800",
  },
  export: {
    label: "Экспорт",
    className: "bg-purple-100 text-purple-800",
  },
  import: {
    label: "Импорт",
    className: "bg-indigo-100 text-indigo-800",
  },
  view: {
    label: "Просмотр",
    className: "bg-cyan-100 text-cyan-800",
  },
  approve: {
    label: "Одобрение",
    className: "bg-emerald-100 text-emerald-800",
  },
  reject: {
    label: "Отклонение",
    className: "bg-rose-100 text-rose-800",
  },
};

export const OBJECT_TYPE_LABELS: Record<AuditObjectType, string> = {
  application: "Заявка",
  client: "Клиент",
  partner: "Партнёр",
  branch: "Филиал",
  user: "Пользователь",
  settings: "Настройки",
};

export const LOG_LEVEL_STYLES: Record<
  SystemLogLevel,
  { label: string; className: string }
> = {
  error: { label: "Error", className: "bg-red-100 text-red-800" },
  warning: { label: "Warning", className: "bg-amber-100 text-amber-800" },
  info: { label: "Info", className: "bg-blue-100 text-blue-800" },
  debug: { label: "Debug", className: "bg-gray-100 text-gray-800" },
};

export const ALERT_SEVERITY_STYLES: Record<
  SecurityAlert["severity"],
  { icon: string; className: string; bgClassName: string }
> = {
  critical: {
    icon: "AlertTriangle",
    className: "text-red-600",
    bgClassName: "bg-red-50 border-red-200",
  },
  warning: {
    icon: "AlertTriangle",
    className: "text-amber-600",
    bgClassName: "bg-amber-50 border-amber-200",
  },
  info: {
    icon: "Info",
    className: "text-blue-600",
    bgClassName: "bg-blue-50 border-blue-200",
  },
};

export const INTEGRATION_SOURCE_LABELS: Record<IntegrationSource, string> = {
  "1c": "1С",
  bnpl: "BNPL-партнёры",
  sms: "SMS",
  email: "Email",
};

export const ALERT_TRIGGERS = [
  "Массовое удаление",
  "Множественные входы",
  "Изменение критических настроек",
  "Подозрительный IP",
  "Неудачные попытки входа",
  "Массовый экспорт",
  "Изменение ролей",
  "Отключение 2FA",
];

// ── Mock users referenced in audit ─────────────────────────────────────

const AUDIT_USERS = [
  { id: "USR-001", name: "Каримов Джамшид", role: "Superadmin" },
  { id: "USR-002", name: "Рахимова Дилноза", role: "Admin" },
  { id: "USR-003", name: "Абдуллаев Бекзод", role: "Admin" },
  { id: "USR-004", name: "Ташматова Нигора", role: "Operator" },
  { id: "USR-005", name: "Юлдашев Фаррух", role: "Operator" },
  { id: "USR-006", name: "Мирзаева Зулхумор", role: "Operator" },
  { id: "USR-007", name: "Хасанов Ойбек", role: "Agent" },
  { id: "USR-008", name: "Садикова Малика", role: "Agent" },
];

const IPS = [
  { ip: "195.158.31.42", city: "Ташкент", country: "UZ" },
  { ip: "195.158.31.45", city: "Ташкент", country: "UZ" },
  { ip: "213.230.96.18", city: "Самарканд", country: "UZ" },
  { ip: "185.74.5.201", city: "Бухара", country: "UZ" },
  { ip: "91.213.98.7", city: "Фергана", country: "UZ" },
  { ip: "45.132.74.19", city: "Москва", country: "RU" },
  { ip: "172.16.0.1", city: "VPN", country: "—" },
];

const USER_AGENTS = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/125.0.0.0",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) Safari/17.5",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5) Mobile/15E148",
  "Mozilla/5.0 (Linux; Android 14) Chrome/125.0.6422.0 Mobile",
];

// ── Helper ─────────────────────────────────────────────────────────────

function d(daysAgo: number, hours = 10, minutes = 0, seconds = 0): Date {
  const date = new Date(2026, 4, 24); // May 24, 2026
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hours, minutes, seconds, Math.floor(Math.random() * 999));
  return date;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ── Audit Entries (50) ─────────────────────────────────────────────────

export const AUDIT_ENTRIES: AuditEntry[] = [
  {
    id: "AUD-001",
    timestamp: d(0, 9, 45, 12),
    ...AUDIT_USERS[0],
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-a1b2c3d4",
    sessionId: "sess-001-abc",
    actionType: "update",
    objectType: "application",
    objectId: "BR-12483",
    objectLabel: "Заявка BR-12483",
    objectHref: "/applications/BR-12483",
    changes: [
      { field: "Статус", oldValue: "На скоринге", newValue: "Одобрена" },
      {
        field: "Сумма одобрения",
        oldValue: "0 UZS",
        newValue: "15 000 000 UZS",
      },
    ],
    oldJson: {
      status: "scoring",
      approvedAmount: 0,
      updatedAt: "2026-05-24T09:30:00Z",
    },
    newJson: {
      status: "approved",
      approvedAmount: 15000000,
      updatedAt: "2026-05-24T09:45:12Z",
    },
    relatedEntryIds: ["AUD-002"],
  },
  {
    id: "AUD-002",
    timestamp: d(0, 9, 45, 13),
    ...AUDIT_USERS[0],
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-a1b2c3d5",
    sessionId: "sess-001-abc",
    actionType: "update",
    objectType: "client",
    objectId: "CL-00428",
    objectLabel: "Клиент CL-00428",
    objectHref: "/clients/CL-00428",
    changes: [
      { field: "Скоринг", oldValue: "72", newValue: "78" },
      {
        field: "Активные рассрочки",
        oldValue: "1",
        newValue: "2",
      },
    ],
    oldJson: { scoring: 72, activeInstallments: 1 },
    newJson: { scoring: 78, activeInstallments: 2 },
    relatedEntryIds: ["AUD-001"],
  },
  {
    id: "AUD-003",
    timestamp: d(0, 9, 30, 5),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-login-001",
    sessionId: "sess-001-abc",
    actionType: "login",
    objectType: "user",
    objectId: "USR-001",
    objectLabel: "Каримов Джамшид",
    objectHref: "/users/USR-001",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-004",
    timestamp: d(0, 10, 15, 22),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-e5f6g7h8",
    sessionId: "sess-004-def",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12501",
    objectLabel: "Заявка BR-12501",
    objectHref: "/applications/BR-12501",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Усманов Рустам" },
      { field: "Сумма", oldValue: "—", newValue: "8 500 000 UZS" },
      { field: "Партнёр", oldValue: "—", newValue: "Alif Nasiya" },
    ],
    oldJson: {},
    newJson: {
      clientName: "Усманов Рустам",
      amount: 8500000,
      partner: "Alif Nasiya",
      status: "new",
    },
    relatedEntryIds: [],
  },
  {
    id: "AUD-005",
    timestamp: d(0, 11, 2, 44),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-i9j0k1l2",
    sessionId: "sess-002-ghi",
    actionType: "update",
    objectType: "partner",
    objectId: "P-002",
    objectLabel: "Партнёр Anorbank",
    objectHref: "/partners/P-002",
    changes: [
      { field: "Статус API", oldValue: "Активен", newValue: "Недоступен" },
    ],
    oldJson: { apiStatus: "active", lastCheck: "2026-05-24T10:55:00Z" },
    newJson: { apiStatus: "unavailable", lastCheck: "2026-05-24T11:02:44Z" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-006",
    timestamp: d(0, 11, 30, 8),
    userId: AUDIT_USERS[4].id,
    userName: AUDIT_USERS[4].name,
    userRole: AUDIT_USERS[4].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-m3n4o5p6",
    sessionId: "sess-005-jkl",
    actionType: "export",
    objectType: "application",
    objectId: "—",
    objectLabel: "Экспорт заявок (147 записей)",
    objectHref: "/applications",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-007",
    timestamp: d(0, 12, 5, 33),
    userId: AUDIT_USERS[2].id,
    userName: AUDIT_USERS[2].name,
    userRole: AUDIT_USERS[2].role,
    ip: IPS[3].ip,
    ipCity: IPS[3].city,
    ipCountry: IPS[3].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-q7r8s9t0",
    sessionId: "sess-003-mno",
    actionType: "delete",
    objectType: "user",
    objectId: "USR-012",
    objectLabel: "Пользователь Nazarov A.",
    objectHref: "/users/USR-012",
    changes: [
      { field: "Статус", oldValue: "Деактивирован", newValue: "Удалён" },
    ],
    oldJson: {
      id: "USR-012",
      name: "Nazarov Aziz",
      status: "deactivated",
      role: "agent",
    },
    newJson: null as unknown as Record<string, unknown>,
    relatedEntryIds: [],
  },
  {
    id: "AUD-008",
    timestamp: d(0, 13, 20, 17),
    userId: AUDIT_USERS[5].id,
    userName: AUDIT_USERS[5].name,
    userRole: AUDIT_USERS[5].role,
    ip: IPS[4].ip,
    ipCity: IPS[4].city,
    ipCountry: IPS[4].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-u1v2w3x4",
    sessionId: "sess-006-pqr",
    actionType: "approve",
    objectType: "application",
    objectId: "BR-12478",
    objectLabel: "Заявка BR-12478",
    objectHref: "/applications/BR-12478",
    changes: [
      { field: "Статус", oldValue: "На скоринге", newValue: "Одобрена" },
      {
        field: "Сумма одобрения",
        oldValue: "0 UZS",
        newValue: "22 000 000 UZS",
      },
    ],
    oldJson: { status: "scoring", approvedAmount: 0 },
    newJson: { status: "approved", approvedAmount: 22000000 },
    relatedEntryIds: [],
  },
  {
    id: "AUD-009",
    timestamp: d(0, 14, 0, 0),
    userId: AUDIT_USERS[6].id,
    userName: AUDIT_USERS[6].name,
    userRole: AUDIT_USERS[6].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[2],
    requestId: "req-y5z6a7b8",
    sessionId: "sess-007-stu",
    actionType: "view",
    objectType: "client",
    objectId: "CL-00312",
    objectLabel: "Клиент CL-00312",
    objectHref: "/clients/CL-00312",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-010",
    timestamp: d(0, 14, 30, 55),
    userId: AUDIT_USERS[7].id,
    userName: AUDIT_USERS[7].name,
    userRole: AUDIT_USERS[7].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-c9d0e1f2",
    sessionId: "sess-008-vwx",
    actionType: "reject",
    objectType: "application",
    objectId: "BR-12490",
    objectLabel: "Заявка BR-12490",
    objectHref: "/applications/BR-12490",
    changes: [
      { field: "Статус", oldValue: "На рассмотрении", newValue: "Отклонена" },
      {
        field: "Причина отклонения",
        oldValue: "—",
        newValue: "Недостаточный скоринг",
      },
    ],
    oldJson: { status: "in_progress", rejectReason: null },
    newJson: {
      status: "rejected",
      rejectReason: "Недостаточный скоринг",
    },
    relatedEntryIds: [],
  },
  {
    id: "AUD-011",
    timestamp: d(0, 15, 10, 28),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-g3h4i5j6",
    sessionId: "sess-001-abc",
    actionType: "update",
    objectType: "settings",
    objectId: "security",
    objectLabel: "Настройки безопасности",
    objectHref: "/settings",
    changes: [
      { field: "Мин. длина пароля", oldValue: "8", newValue: "12" },
      {
        field: "Принудительная 2FA",
        oldValue: "Superadmin",
        newValue: "Superadmin, Admin",
      },
    ],
    oldJson: { minPasswordLength: 8, forced2FA: ["superadmin"] },
    newJson: { minPasswordLength: 12, forced2FA: ["superadmin", "admin"] },
    relatedEntryIds: [],
  },
  {
    id: "AUD-012",
    timestamp: d(0, 16, 0, 0),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-k7l8m9n0",
    sessionId: "sess-002-ghi",
    actionType: "logout",
    objectType: "user",
    objectId: "USR-002",
    objectLabel: "Рахимова Дилноза",
    objectHref: "/users/USR-002",
    changes: [],
    relatedEntryIds: [],
  },
  // Day -1 entries
  {
    id: "AUD-013",
    timestamp: d(1, 8, 15, 0),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-o1p2q3r4",
    sessionId: "sess-004-yz1",
    actionType: "login",
    objectType: "user",
    objectId: "USR-004",
    objectLabel: "Ташматова Нигора",
    objectHref: "/users/USR-004",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-014",
    timestamp: d(1, 8, 45, 33),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-s5t6u7v8",
    sessionId: "sess-004-yz1",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12496",
    objectLabel: "Заявка BR-12496",
    objectHref: "/applications/BR-12496",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Кадырова Ш." },
      { field: "Сумма", oldValue: "—", newValue: "5 200 000 UZS" },
    ],
    oldJson: {},
    newJson: {
      clientName: "Кадырова Шахноза",
      amount: 5200000,
      partner: "Uzum Nasiya",
    },
    relatedEntryIds: [],
  },
  {
    id: "AUD-015",
    timestamp: d(1, 9, 12, 17),
    userId: AUDIT_USERS[4].id,
    userName: AUDIT_USERS[4].name,
    userRole: AUDIT_USERS[4].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-w9x0y1z2",
    sessionId: "sess-005-ab2",
    actionType: "update",
    objectType: "application",
    objectId: "BR-12480",
    objectLabel: "Заявка BR-12480",
    objectHref: "/applications/BR-12480",
    changes: [
      { field: "Статус", oldValue: "Новая", newValue: "На скоринге" },
    ],
    oldJson: { status: "new" },
    newJson: { status: "scoring" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-016",
    timestamp: d(1, 10, 30, 5),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-a3b4c5d6",
    sessionId: "sess-002-cd3",
    actionType: "update",
    objectType: "branch",
    objectId: "BR-001",
    objectLabel: "Филиал Ташкент-Центр",
    objectHref: "/branches/BR-001",
    changes: [
      { field: "Менеджер", oldValue: "Юлдашев Ф.", newValue: "Хасанов О." },
    ],
    oldJson: { managerId: "USR-005", managerName: "Юлдашев Фаррух" },
    newJson: { managerId: "USR-007", managerName: "Хасанов Ойбек" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-017",
    timestamp: d(1, 11, 0, 0),
    userId: AUDIT_USERS[2].id,
    userName: AUDIT_USERS[2].name,
    userRole: AUDIT_USERS[2].role,
    ip: IPS[3].ip,
    ipCity: IPS[3].city,
    ipCountry: IPS[3].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-e7f8g9h0",
    sessionId: "sess-003-ef4",
    actionType: "create",
    objectType: "user",
    objectId: "USR-013",
    objectLabel: "Пользователь Алимов Б.",
    objectHref: "/users/USR-013",
    changes: [
      { field: "Роль", oldValue: "—", newValue: "Оператор" },
      { field: "Филиал", oldValue: "—", newValue: "Самарканд" },
    ],
    oldJson: {},
    newJson: {
      id: "USR-013",
      name: "Алимов Бахтиёр",
      role: "operator",
      branch: "Самарканд",
    },
    relatedEntryIds: [],
  },
  {
    id: "AUD-018",
    timestamp: d(1, 12, 15, 44),
    userId: AUDIT_USERS[5].id,
    userName: AUDIT_USERS[5].name,
    userRole: AUDIT_USERS[5].role,
    ip: IPS[4].ip,
    ipCity: IPS[4].city,
    ipCountry: IPS[4].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-i1j2k3l4",
    sessionId: "sess-006-gh5",
    actionType: "update",
    objectType: "application",
    objectId: "BR-12475",
    objectLabel: "Заявка BR-12475",
    objectHref: "/applications/BR-12475",
    changes: [
      { field: "Статус", oldValue: "Одобрена", newValue: "Завершена" },
      {
        field: "Дата выдачи",
        oldValue: "—",
        newValue: "23.05.2026",
      },
    ],
    oldJson: { status: "approved", issuedAt: null },
    newJson: { status: "completed", issuedAt: "2026-05-23T12:15:44Z" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-019",
    timestamp: d(1, 13, 45, 22),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-m5n6o7p8",
    sessionId: "sess-001-ij6",
    actionType: "update",
    objectType: "partner",
    objectId: "P-001",
    objectLabel: "Партнёр Alif Nasiya",
    objectHref: "/partners/P-001",
    changes: [
      { field: "Комиссия", oldValue: "2.5%", newValue: "3.0%" },
      { field: "Мин. сумма", oldValue: "1 000 000 UZS", newValue: "500 000 UZS" },
    ],
    oldJson: { commissionRate: 2.5, minAmount: 1000000 },
    newJson: { commissionRate: 3.0, minAmount: 500000 },
    relatedEntryIds: [],
  },
  {
    id: "AUD-020",
    timestamp: d(1, 14, 20, 0),
    userId: AUDIT_USERS[6].id,
    userName: AUDIT_USERS[6].name,
    userRole: AUDIT_USERS[6].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[2],
    requestId: "req-q9r0s1t2",
    sessionId: "sess-007-kl7",
    actionType: "view",
    objectType: "application",
    objectId: "BR-12490",
    objectLabel: "Заявка BR-12490",
    objectHref: "/applications/BR-12490",
    changes: [],
    relatedEntryIds: [],
  },
  // Day -2 entries
  {
    id: "AUD-021",
    timestamp: d(2, 8, 0, 0),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-u3v4w5x6",
    sessionId: "sess-002-mn8",
    actionType: "login",
    objectType: "user",
    objectId: "USR-002",
    objectLabel: "Рахимова Дилноза",
    objectHref: "/users/USR-002",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-022",
    timestamp: d(2, 9, 15, 30),
    userId: AUDIT_USERS[4].id,
    userName: AUDIT_USERS[4].name,
    userRole: AUDIT_USERS[4].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-y7z8a9b0",
    sessionId: "sess-005-op9",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12472",
    objectLabel: "Заявка BR-12472",
    objectHref: "/applications/BR-12472",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Ибрагимов Т." },
      { field: "Сумма", oldValue: "—", newValue: "12 000 000 UZS" },
    ],
    oldJson: {},
    newJson: {
      clientName: "Ибрагимов Тимур",
      amount: 12000000,
      partner: "Iman",
    },
    relatedEntryIds: [],
  },
  {
    id: "AUD-023",
    timestamp: d(2, 10, 0, 18),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-c1d2e3f4",
    sessionId: "sess-001-qr0",
    actionType: "update",
    objectType: "settings",
    objectId: "integrations",
    objectLabel: "Настройки интеграций",
    objectHref: "/settings",
    changes: [
      { field: "SMS-провайдер", oldValue: "Eskiz", newValue: "Playmobile" },
    ],
    oldJson: { smsProvider: "eskiz" },
    newJson: { smsProvider: "playmobile" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-024",
    timestamp: d(2, 11, 30, 0),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-g5h6i7j8",
    sessionId: "sess-004-st1",
    actionType: "update",
    objectType: "client",
    objectId: "CL-00315",
    objectLabel: "Клиент CL-00315",
    objectHref: "/clients/CL-00315",
    changes: [
      { field: "Телефон", oldValue: "+998 90 123-45-67", newValue: "+998 91 987-65-43" },
    ],
    oldJson: { phone: "+998901234567" },
    newJson: { phone: "+998919876543" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-025",
    timestamp: d(2, 12, 0, 22),
    userId: AUDIT_USERS[7].id,
    userName: AUDIT_USERS[7].name,
    userRole: AUDIT_USERS[7].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-k9l0m1n2",
    sessionId: "sess-008-uv2",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12468",
    objectLabel: "Заявка BR-12468",
    objectHref: "/applications/BR-12468",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Мамадалиев Р." },
      { field: "Сумма", oldValue: "—", newValue: "3 800 000 UZS" },
    ],
    oldJson: {},
    newJson: {
      clientName: "Мамадалиев Равшан",
      amount: 3800000,
      partner: "Multicard",
    },
    relatedEntryIds: [],
  },
  // Day -3 entries
  {
    id: "AUD-026",
    timestamp: d(3, 8, 30, 0),
    userId: AUDIT_USERS[2].id,
    userName: AUDIT_USERS[2].name,
    userRole: AUDIT_USERS[2].role,
    ip: IPS[3].ip,
    ipCity: IPS[3].city,
    ipCountry: IPS[3].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-o3p4q5r6",
    sessionId: "sess-003-wx3",
    actionType: "update",
    objectType: "partner",
    objectId: "P-003",
    objectLabel: "Партнёр Uzum Nasiya",
    objectHref: "/partners/P-003",
    changes: [
      { field: "Регион", oldValue: "Ташкент, Самарканд", newValue: "Ташкент, Самарканд, Бухара" },
    ],
    oldJson: { regions: ["tashkent", "samarkand"] },
    newJson: { regions: ["tashkent", "samarkand", "bukhara"] },
    relatedEntryIds: [],
  },
  {
    id: "AUD-027",
    timestamp: d(3, 9, 0, 15),
    userId: AUDIT_USERS[5].id,
    userName: AUDIT_USERS[5].name,
    userRole: AUDIT_USERS[5].role,
    ip: IPS[4].ip,
    ipCity: IPS[4].city,
    ipCountry: IPS[4].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-s7t8u9v0",
    sessionId: "sess-006-yz4",
    actionType: "approve",
    objectType: "application",
    objectId: "BR-12460",
    objectLabel: "Заявка BR-12460",
    objectHref: "/applications/BR-12460",
    changes: [
      { field: "Статус", oldValue: "На скоринге", newValue: "Одобрена" },
    ],
    oldJson: { status: "scoring" },
    newJson: { status: "approved" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-028",
    timestamp: d(3, 10, 45, 30),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-w1x2y3z4",
    sessionId: "sess-001-ab5",
    actionType: "import",
    objectType: "client",
    objectId: "—",
    objectLabel: "Импорт клиентов (32 записи)",
    objectHref: "/clients",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-029",
    timestamp: d(3, 11, 20, 10),
    userId: AUDIT_USERS[4].id,
    userName: AUDIT_USERS[4].name,
    userRole: AUDIT_USERS[4].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-a5b6c7d8",
    sessionId: "sess-005-cd6",
    actionType: "update",
    objectType: "application",
    objectId: "BR-12455",
    objectLabel: "Заявка BR-12455",
    objectHref: "/applications/BR-12455",
    changes: [
      { field: "Статус", oldValue: "Одобрена", newValue: "Ожидает документов" },
    ],
    oldJson: { status: "approved" },
    newJson: { status: "awaiting_docs" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-030",
    timestamp: d(3, 13, 0, 0),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-e9f0g1h2",
    sessionId: "sess-002-ef7",
    actionType: "export",
    objectType: "client",
    objectId: "—",
    objectLabel: "Экспорт клиентов (85 записей)",
    objectHref: "/clients",
    changes: [],
    relatedEntryIds: [],
  },
  // Day -4 entries
  {
    id: "AUD-031",
    timestamp: d(4, 8, 0, 0),
    userId: AUDIT_USERS[6].id,
    userName: AUDIT_USERS[6].name,
    userRole: AUDIT_USERS[6].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[2],
    requestId: "req-i3j4k5l6",
    sessionId: "sess-007-gh8",
    actionType: "login",
    objectType: "user",
    objectId: "USR-007",
    objectLabel: "Хасанов Ойбек",
    objectHref: "/users/USR-007",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-032",
    timestamp: d(4, 9, 30, 0),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-m7n8o9p0",
    sessionId: "sess-004-ij9",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12450",
    objectLabel: "Заявка BR-12450",
    objectHref: "/applications/BR-12450",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Рашидов Б." },
      { field: "Сумма", oldValue: "—", newValue: "18 500 000 UZS" },
    ],
    oldJson: {},
    newJson: {
      clientName: "Рашидов Бобур",
      amount: 18500000,
      partner: "Asia Alliance",
    },
    relatedEntryIds: [],
  },
  {
    id: "AUD-033",
    timestamp: d(4, 10, 15, 0),
    userId: AUDIT_USERS[2].id,
    userName: AUDIT_USERS[2].name,
    userRole: AUDIT_USERS[2].role,
    ip: IPS[3].ip,
    ipCity: IPS[3].city,
    ipCountry: IPS[3].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-q1r2s3t4",
    sessionId: "sess-003-kl0",
    actionType: "update",
    objectType: "user",
    objectId: "USR-008",
    objectLabel: "Пользователь Садикова М.",
    objectHref: "/users/USR-008",
    changes: [
      { field: "Роль", oldValue: "Agent", newValue: "Operator" },
    ],
    oldJson: { role: "agent" },
    newJson: { role: "operator" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-034",
    timestamp: d(4, 11, 0, 0),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-u5v6w7x8",
    sessionId: "sess-001-mn1",
    actionType: "update",
    objectType: "settings",
    objectId: "general",
    objectLabel: "Общие настройки",
    objectHref: "/settings",
    changes: [
      { field: "Часовой пояс", oldValue: "UTC+5", newValue: "Asia/Tashkent" },
    ],
    oldJson: { timezone: "UTC+5" },
    newJson: { timezone: "Asia/Tashkent" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-035",
    timestamp: d(4, 12, 30, 0),
    userId: AUDIT_USERS[7].id,
    userName: AUDIT_USERS[7].name,
    userRole: AUDIT_USERS[7].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-y9z0a1b2",
    sessionId: "sess-008-op2",
    actionType: "update",
    objectType: "application",
    objectId: "BR-12445",
    objectLabel: "Заявка BR-12445",
    objectHref: "/applications/BR-12445",
    changes: [
      { field: "Статус", oldValue: "Новая", newValue: "На скоринге" },
    ],
    oldJson: { status: "new" },
    newJson: { status: "scoring" },
    relatedEntryIds: [],
  },
  // Day -5
  {
    id: "AUD-036",
    timestamp: d(5, 9, 0, 0),
    userId: AUDIT_USERS[5].id,
    userName: AUDIT_USERS[5].name,
    userRole: AUDIT_USERS[5].role,
    ip: IPS[4].ip,
    ipCity: IPS[4].city,
    ipCountry: IPS[4].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-c3d4e5f6",
    sessionId: "sess-006-qr3",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12440",
    objectLabel: "Заявка BR-12440",
    objectHref: "/applications/BR-12440",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Нурматов А." },
      { field: "Сумма", oldValue: "—", newValue: "6 700 000 UZS" },
    ],
    oldJson: {},
    newJson: { clientName: "Нурматов Акмаль", amount: 6700000, partner: "Iman" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-037",
    timestamp: d(5, 10, 30, 0),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-g7h8i9j0",
    sessionId: "sess-002-st4",
    actionType: "update",
    objectType: "branch",
    objectId: "BR-003",
    objectLabel: "Филиал Самарканд",
    objectHref: "/branches/BR-003",
    changes: [
      { field: "Статус", oldValue: "Активен", newValue: "Неактивен" },
    ],
    oldJson: { status: "active" },
    newJson: { status: "inactive" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-038",
    timestamp: d(5, 11, 45, 0),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-k1l2m3n4",
    sessionId: "sess-001-uv5",
    actionType: "delete",
    objectType: "partner",
    objectId: "P-007",
    objectLabel: "Партнёр TestBank",
    objectHref: "/partners",
    changes: [
      { field: "Статус", oldValue: "Тестовый", newValue: "Удалён" },
    ],
    oldJson: { id: "P-007", name: "TestBank", status: "test" },
    newJson: null as unknown as Record<string, unknown>,
    relatedEntryIds: [],
  },
  {
    id: "AUD-039",
    timestamp: d(5, 14, 0, 0),
    userId: AUDIT_USERS[4].id,
    userName: AUDIT_USERS[4].name,
    userRole: AUDIT_USERS[4].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-o5p6q7r8",
    sessionId: "sess-005-wx6",
    actionType: "reject",
    objectType: "application",
    objectId: "BR-12438",
    objectLabel: "Заявка BR-12438",
    objectHref: "/applications/BR-12438",
    changes: [
      { field: "Статус", oldValue: "На скоринге", newValue: "Отклонена" },
      { field: "Причина", oldValue: "—", newValue: "Чёрный список" },
    ],
    oldJson: { status: "scoring" },
    newJson: { status: "rejected", rejectReason: "Чёрный список" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-040",
    timestamp: d(5, 15, 30, 0),
    userId: AUDIT_USERS[6].id,
    userName: AUDIT_USERS[6].name,
    userRole: AUDIT_USERS[6].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[2],
    requestId: "req-s9t0u1v2",
    sessionId: "sess-007-yz7",
    actionType: "view",
    objectType: "partner",
    objectId: "P-004",
    objectLabel: "Партнёр Iman",
    objectHref: "/partners/P-004",
    changes: [],
    relatedEntryIds: [],
  },
  // Day -6, -7
  {
    id: "AUD-041",
    timestamp: d(6, 9, 0, 0),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[5].ip,
    ipCity: IPS[5].city,
    ipCountry: IPS[5].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-w3x4y5z6",
    sessionId: "sess-001-ab8",
    actionType: "login",
    objectType: "user",
    objectId: "USR-001",
    objectLabel: "Каримов Джамшид",
    objectHref: "/users/USR-001",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-042",
    timestamp: d(6, 10, 0, 0),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-a7b8c9d0",
    sessionId: "sess-004-cd9",
    actionType: "create",
    objectType: "application",
    objectId: "BR-12430",
    objectLabel: "Заявка BR-12430",
    objectHref: "/applications/BR-12430",
    changes: [
      { field: "Клиент", oldValue: "—", newValue: "Исмаилов К." },
      { field: "Сумма", oldValue: "—", newValue: "9 200 000 UZS" },
    ],
    oldJson: {},
    newJson: { clientName: "Исмаилов Камол", amount: 9200000, partner: "Alif Nasiya" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-043",
    timestamp: d(6, 11, 0, 0),
    userId: AUDIT_USERS[2].id,
    userName: AUDIT_USERS[2].name,
    userRole: AUDIT_USERS[2].role,
    ip: IPS[3].ip,
    ipCity: IPS[3].city,
    ipCountry: IPS[3].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-e1f2g3h4",
    sessionId: "sess-003-ef0",
    actionType: "update",
    objectType: "user",
    objectId: "USR-006",
    objectLabel: "Пользователь Мирзаева З.",
    objectHref: "/users/USR-006",
    changes: [
      { field: "2FA", oldValue: "Выключена", newValue: "Включена" },
    ],
    oldJson: { twoFactorEnabled: false },
    newJson: { twoFactorEnabled: true },
    relatedEntryIds: [],
  },
  {
    id: "AUD-044",
    timestamp: d(6, 14, 0, 0),
    userId: AUDIT_USERS[1].id,
    userName: AUDIT_USERS[1].name,
    userRole: AUDIT_USERS[1].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-i5j6k7l8",
    sessionId: "sess-002-gh1",
    actionType: "export",
    objectType: "application",
    objectId: "—",
    objectLabel: "Экспорт заявок (312 записей)",
    objectHref: "/applications",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-045",
    timestamp: d(7, 8, 0, 0),
    userId: AUDIT_USERS[7].id,
    userName: AUDIT_USERS[7].name,
    userRole: AUDIT_USERS[7].role,
    ip: IPS[2].ip,
    ipCity: IPS[2].city,
    ipCountry: IPS[2].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-m9n0o1p2",
    sessionId: "sess-008-ij2",
    actionType: "login",
    objectType: "user",
    objectId: "USR-008",
    objectLabel: "Садикова Малика",
    objectHref: "/users/USR-008",
    changes: [],
    relatedEntryIds: [],
  },
  {
    id: "AUD-046",
    timestamp: d(7, 9, 30, 0),
    userId: AUDIT_USERS[5].id,
    userName: AUDIT_USERS[5].name,
    userRole: AUDIT_USERS[5].role,
    ip: IPS[4].ip,
    ipCity: IPS[4].city,
    ipCountry: IPS[4].country,
    userAgent: USER_AGENTS[3],
    requestId: "req-q3r4s5t6",
    sessionId: "sess-006-kl3",
    actionType: "approve",
    objectType: "application",
    objectId: "BR-12425",
    objectLabel: "Заявка BR-12425",
    objectHref: "/applications/BR-12425",
    changes: [
      { field: "Статус", oldValue: "На скоринге", newValue: "Одобрена" },
    ],
    oldJson: { status: "scoring" },
    newJson: { status: "approved" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-047",
    timestamp: d(7, 10, 45, 0),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-u7v8w9x0",
    sessionId: "sess-001-mn4",
    actionType: "update",
    objectType: "partner",
    objectId: "P-005",
    objectLabel: "Партнёр Multicard",
    objectHref: "/partners/P-005",
    changes: [
      { field: "API ключ", oldValue: "****a1b2", newValue: "****c3d4" },
    ],
    oldJson: { apiKeyLast4: "a1b2" },
    newJson: { apiKeyLast4: "c3d4" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-048",
    timestamp: d(7, 12, 0, 0),
    userId: AUDIT_USERS[3].id,
    userName: AUDIT_USERS[3].name,
    userRole: AUDIT_USERS[3].role,
    ip: IPS[1].ip,
    ipCity: IPS[1].city,
    ipCountry: IPS[1].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-y1z2a3b4",
    sessionId: "sess-004-op5",
    actionType: "update",
    objectType: "application",
    objectId: "BR-12420",
    objectLabel: "Заявка BR-12420",
    objectHref: "/applications/BR-12420",
    changes: [
      { field: "Комментарий", oldValue: "—", newValue: "Клиент запросил увеличение суммы" },
    ],
    oldJson: { comment: null },
    newJson: { comment: "Клиент запросил увеличение суммы" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-049",
    timestamp: d(7, 14, 0, 0),
    userId: AUDIT_USERS[2].id,
    userName: AUDIT_USERS[2].name,
    userRole: AUDIT_USERS[2].role,
    ip: IPS[3].ip,
    ipCity: IPS[3].city,
    ipCountry: IPS[3].country,
    userAgent: USER_AGENTS[1],
    requestId: "req-c5d6e7f8",
    sessionId: "sess-003-qr6",
    actionType: "update",
    objectType: "branch",
    objectId: "BR-005",
    objectLabel: "Филиал Фергана",
    objectHref: "/branches/BR-005",
    changes: [
      { field: "Режим работы", oldValue: "09:00–18:00", newValue: "08:00–19:00" },
    ],
    oldJson: { workingHours: "09:00-18:00" },
    newJson: { workingHours: "08:00-19:00" },
    relatedEntryIds: [],
  },
  {
    id: "AUD-050",
    timestamp: d(7, 16, 0, 0),
    userId: AUDIT_USERS[0].id,
    userName: AUDIT_USERS[0].name,
    userRole: AUDIT_USERS[0].role,
    ip: IPS[0].ip,
    ipCity: IPS[0].city,
    ipCountry: IPS[0].country,
    userAgent: USER_AGENTS[0],
    requestId: "req-g9h0i1j2",
    sessionId: "sess-001-st7",
    actionType: "logout",
    objectType: "user",
    objectId: "USR-001",
    objectLabel: "Каримов Джамшид",
    objectHref: "/users/USR-001",
    changes: [],
    relatedEntryIds: [],
  },
];

// ── System Logs (20) ───────────────────────────────────────────────────

export const SYSTEM_LOGS: SystemLogEntry[] = [
  {
    id: "SYS-001",
    timestamp: d(0, 9, 42, 15),
    level: "error",
    component: "AuthService",
    message: "Failed to verify 2FA token for user USR-012: Token expired",
    stackTrace: `Error: Token expired
  at AuthService.verify2FA (auth-service.ts:142)
  at POST /api/auth/2fa/verify (routes/auth.ts:87)
  at Layer.handle (express/lib/router/layer.js:95)
  at next (express/lib/router/route.js:144)
  at Route.dispatch (express/lib/router/route.js:114)`,
  },
  {
    id: "SYS-002",
    timestamp: d(0, 9, 43, 0),
    level: "warning",
    component: "RateLimiter",
    message: "Rate limit approaching for IP 195.158.31.42: 45/50 requests in 60s window",
  },
  {
    id: "SYS-003",
    timestamp: d(0, 10, 0, 0),
    level: "info",
    component: "CacheManager",
    message: "Cache invalidation completed: 1,247 keys removed, 3,892 keys retained",
  },
  {
    id: "SYS-004",
    timestamp: d(0, 10, 15, 0),
    level: "debug",
    component: "QueryOptimizer",
    message: "Slow query detected: SELECT * FROM applications WHERE ... (2,340ms, 15,420 rows scanned)",
  },
  {
    id: "SYS-005",
    timestamp: d(0, 11, 0, 0),
    level: "error",
    component: "ScoringEngine",
    message: "Scoring calculation failed for application BR-12499: Division by zero in debt_ratio",
    stackTrace: `ArithmeticError: Division by zero
  at ScoringEngine.calculateDebtRatio (scoring-engine.ts:215)
  at ScoringEngine.processApplication (scoring-engine.ts:89)
  at ScoringQueue.processNext (scoring-queue.ts:44)
  at Timer.processTimers (internal/timers.js:500)`,
  },
  {
    id: "SYS-006",
    timestamp: d(0, 12, 30, 0),
    level: "warning",
    component: "DatabasePool",
    message: "Connection pool utilization at 85% (17/20 connections active)",
  },
  {
    id: "SYS-007",
    timestamp: d(0, 13, 0, 0),
    level: "info",
    component: "BackupService",
    message: "Daily backup completed successfully: 2.3 GB compressed, uploaded to S3",
  },
  {
    id: "SYS-008",
    timestamp: d(0, 14, 0, 0),
    level: "debug",
    component: "WebSocket",
    message: "Active WebSocket connections: 24, messages/sec: 156",
  },
  {
    id: "SYS-009",
    timestamp: d(0, 14, 30, 0),
    level: "error",
    component: "FileStorage",
    message: "Failed to upload document for application BR-12501: Storage quota exceeded",
    stackTrace: `StorageError: Quota exceeded
  at FileStorage.upload (file-storage.ts:78)
  at DocumentService.saveDocument (document-service.ts:134)
  at POST /api/applications/:id/documents (routes/applications.ts:245)`,
  },
  {
    id: "SYS-010",
    timestamp: d(0, 15, 0, 0),
    level: "warning",
    component: "SessionManager",
    message: "Expired sessions cleanup: 142 sessions terminated (older than 24h)",
  },
  {
    id: "SYS-011",
    timestamp: d(1, 8, 0, 0),
    level: "info",
    component: "Scheduler",
    message: "Scheduled tasks executed: 12 reports generated, 3 notifications sent",
  },
  {
    id: "SYS-012",
    timestamp: d(1, 9, 0, 0),
    level: "error",
    component: "EmailService",
    message: "SMTP connection timeout after 30s: smtp.provider.uz:587",
    stackTrace: `TimeoutError: Connection timed out
  at SMTPClient.connect (smtp-client.ts:56)
  at EmailService.sendBatch (email-service.ts:92)
  at NotificationDispatcher.dispatch (notification-dispatcher.ts:178)`,
  },
  {
    id: "SYS-013",
    timestamp: d(1, 10, 30, 0),
    level: "debug",
    component: "APIGateway",
    message: "Request latency p99: 245ms, p95: 120ms, p50: 34ms (last 5 minutes)",
  },
  {
    id: "SYS-014",
    timestamp: d(1, 12, 0, 0),
    level: "warning",
    component: "MemoryMonitor",
    message: "Heap usage at 72% (1.44 GB / 2 GB). GC cycle triggered.",
  },
  {
    id: "SYS-015",
    timestamp: d(2, 9, 0, 0),
    level: "info",
    component: "MigrationRunner",
    message: "Database migration #047 applied successfully: add_scoring_v2_columns",
  },
  {
    id: "SYS-016",
    timestamp: d(2, 11, 0, 0),
    level: "error",
    component: "NotificationService",
    message: "Push notification delivery failed: FCM returned 503 for 12 devices",
    stackTrace: `FCMError: Service Unavailable
  at FCMClient.send (fcm-client.ts:89)
  at NotificationService.sendPush (notification-service.ts:156)
  at BroadcastWorker.processQueue (broadcast-worker.ts:67)`,
  },
  {
    id: "SYS-017",
    timestamp: d(3, 8, 30, 0),
    level: "warning",
    component: "CertManager",
    message: "SSL certificate expiring in 14 days for api.texnomart-broker.uz",
  },
  {
    id: "SYS-018",
    timestamp: d(3, 14, 0, 0),
    level: "debug",
    component: "CacheManager",
    message: "Cache hit ratio: 94.2% (Redis), 87.1% (In-memory L1)",
  },
  {
    id: "SYS-019",
    timestamp: d(4, 10, 0, 0),
    level: "info",
    component: "AuthService",
    message: "Password policy updated: minimum length changed from 8 to 12 characters",
  },
  {
    id: "SYS-020",
    timestamp: d(5, 9, 0, 0),
    level: "error",
    component: "PartnerAPI",
    message: "Anorbank API health check failed: connection refused on port 443",
    stackTrace: `ConnectionError: Connection refused
  at PartnerHealthCheck.ping (partner-health.ts:34)
  at HealthCheckScheduler.runAll (health-scheduler.ts:22)
  at CronJob.fireOnTick (node_modules/cron/lib/cron.js:698)`,
  },
];

// ── Integration Logs (15) ──────────────────────────────────────────────

export const INTEGRATION_LOGS: IntegrationLogEntry[] = [
  {
    id: "INT-001",
    timestamp: d(0, 9, 0, 0),
    source: "1c",
    direction: "outgoing",
    endpoint: "POST /api/v2/clients/sync",
    statusCode: 200,
    durationMs: 1245,
    retryCount: 0,
    requestPayload: JSON.stringify({ action: "sync_clients", batchSize: 100, lastSyncId: "CLN-04521" }, null, 2),
    responsePayload: JSON.stringify({ status: "ok", synced: 87, errors: 0, nextSyncId: "CLN-04608" }, null, 2),
  },
  {
    id: "INT-002",
    timestamp: d(0, 9, 30, 0),
    source: "bnpl",
    direction: "outgoing",
    endpoint: "POST /api/scoring/check",
    statusCode: 200,
    durationMs: 3420,
    retryCount: 0,
    requestPayload: JSON.stringify({ applicationId: "BR-12483", clientId: "CL-00428", amount: 15000000, term: 12 }, null, 2),
    responsePayload: JSON.stringify({ score: 78, decision: "approved", maxAmount: 18000000, conditions: { rate: 22.5 } }, null, 2),
  },
  {
    id: "INT-003",
    timestamp: d(0, 10, 0, 0),
    source: "sms",
    direction: "outgoing",
    endpoint: "POST /api/send",
    statusCode: 200,
    durationMs: 890,
    retryCount: 0,
    requestPayload: JSON.stringify({ phone: "+998901234567", message: "Ваша заявка BR-12483 одобрена. Сумма: 15 000 000 UZS" }, null, 2),
    responsePayload: JSON.stringify({ messageId: "sms-7829", status: "delivered", cost: 150 }, null, 2),
  },
  {
    id: "INT-004",
    timestamp: d(0, 11, 0, 0),
    source: "bnpl",
    direction: "incoming",
    endpoint: "POST /webhooks/partner-callback",
    statusCode: 200,
    durationMs: 45,
    retryCount: 0,
    requestPayload: JSON.stringify({ event: "application_status_update", applicationId: "BR-12478", newStatus: "issued", issuedAt: "2026-05-24T10:58:00Z" }, null, 2),
    responsePayload: JSON.stringify({ received: true }, null, 2),
  },
  {
    id: "INT-005",
    timestamp: d(0, 12, 0, 0),
    source: "email",
    direction: "outgoing",
    endpoint: "POST /api/email/send",
    statusCode: 500,
    durationMs: 30120,
    retryCount: 3,
    requestPayload: JSON.stringify({ to: "admin@texnomart.uz", subject: "Ежедневный отчёт — 24.05.2026", template: "daily_report" }, null, 2),
    responsePayload: JSON.stringify({ error: "SMTP connection timeout", code: "ETIMEDOUT" }, null, 2),
  },
  {
    id: "INT-006",
    timestamp: d(0, 13, 0, 0),
    source: "1c",
    direction: "incoming",
    endpoint: "POST /webhooks/1c/product-update",
    statusCode: 200,
    durationMs: 120,
    retryCount: 0,
    requestPayload: JSON.stringify({ action: "product_catalog_update", products: [{ id: "PRD-001", name: "iPhone 15", price: 14500000 }] }, null, 2),
    responsePayload: JSON.stringify({ status: "ok", processed: 1 }, null, 2),
  },
  {
    id: "INT-007",
    timestamp: d(0, 14, 0, 0),
    source: "bnpl",
    direction: "outgoing",
    endpoint: "POST /api/scoring/check",
    statusCode: 504,
    durationMs: 60000,
    retryCount: 2,
    requestPayload: JSON.stringify({ applicationId: "BR-12501", clientId: "CL-00350", amount: 8500000, term: 6 }, null, 2),
    responsePayload: JSON.stringify({ error: "Gateway timeout", retryAfter: 60 }, null, 2),
  },
  {
    id: "INT-008",
    timestamp: d(1, 9, 0, 0),
    source: "sms",
    direction: "outgoing",
    endpoint: "POST /api/send",
    statusCode: 429,
    durationMs: 150,
    retryCount: 1,
    requestPayload: JSON.stringify({ phone: "+998917654321", message: "Код подтверждения: 847293" }, null, 2),
    responsePayload: JSON.stringify({ error: "Rate limit exceeded", retryAfter: 30 }, null, 2),
  },
  {
    id: "INT-009",
    timestamp: d(1, 10, 0, 0),
    source: "1c",
    direction: "outgoing",
    endpoint: "POST /api/v2/orders/sync",
    statusCode: 200,
    durationMs: 2100,
    retryCount: 0,
    requestPayload: JSON.stringify({ action: "sync_orders", from: "2026-05-22T00:00:00Z", to: "2026-05-23T23:59:59Z" }, null, 2),
    responsePayload: JSON.stringify({ status: "ok", synced: 245, errors: 3 }, null, 2),
  },
  {
    id: "INT-010",
    timestamp: d(1, 12, 0, 0),
    source: "email",
    direction: "outgoing",
    endpoint: "POST /api/email/send",
    statusCode: 200,
    durationMs: 1500,
    retryCount: 0,
    requestPayload: JSON.stringify({ to: "client@mail.uz", subject: "Ваша заявка одобрена", template: "application_approved" }, null, 2),
    responsePayload: JSON.stringify({ messageId: "email-12847", status: "sent" }, null, 2),
  },
  {
    id: "INT-011",
    timestamp: d(2, 8, 0, 0),
    source: "bnpl",
    direction: "outgoing",
    endpoint: "GET /api/partner/health",
    statusCode: 503,
    durationMs: 5000,
    retryCount: 3,
    requestPayload: JSON.stringify({ partnerId: "P-002", check: "connectivity" }, null, 2),
    responsePayload: JSON.stringify({ error: "Service unavailable", message: "Maintenance window" }, null, 2),
  },
  {
    id: "INT-012",
    timestamp: d(2, 10, 0, 0),
    source: "sms",
    direction: "outgoing",
    endpoint: "POST /api/send-batch",
    statusCode: 200,
    durationMs: 4500,
    retryCount: 0,
    requestPayload: JSON.stringify({ phones: ["list of 50 phones"], template: "payment_reminder", batchId: "batch-042" }, null, 2),
    responsePayload: JSON.stringify({ batchId: "batch-042", total: 50, delivered: 47, failed: 3 }, null, 2),
  },
  {
    id: "INT-013",
    timestamp: d(3, 9, 0, 0),
    source: "1c",
    direction: "outgoing",
    endpoint: "POST /api/v2/clients/sync",
    statusCode: 401,
    durationMs: 200,
    retryCount: 0,
    requestPayload: JSON.stringify({ action: "sync_clients", batchSize: 100 }, null, 2),
    responsePayload: JSON.stringify({ error: "Unauthorized", message: "API key expired" }, null, 2),
  },
  {
    id: "INT-014",
    timestamp: d(4, 11, 0, 0),
    source: "bnpl",
    direction: "incoming",
    endpoint: "POST /webhooks/partner-callback",
    statusCode: 200,
    durationMs: 38,
    retryCount: 0,
    requestPayload: JSON.stringify({ event: "partner_terms_updated", partnerId: "P-001", changes: { maxAmount: 25000000 } }, null, 2),
    responsePayload: JSON.stringify({ received: true }, null, 2),
  },
  {
    id: "INT-015",
    timestamp: d(5, 14, 0, 0),
    source: "email",
    direction: "outgoing",
    endpoint: "POST /api/email/send-batch",
    statusCode: 200,
    durationMs: 8900,
    retryCount: 0,
    requestPayload: JSON.stringify({ template: "weekly_report", recipients: 12, subject: "Еженедельный отчёт" }, null, 2),
    responsePayload: JSON.stringify({ sent: 12, bounced: 0 }, null, 2),
  },
];

// ── Security Alerts (10) ───────────────────────────────────────────────

export const SECURITY_ALERTS: SecurityAlert[] = [
  {
    id: "SEC-001",
    timestamp: d(0, 3, 15, 0),
    severity: "critical",
    title: "Множественные неудачные попытки входа",
    description: "5 неудачных попыток входа для пользователя USR-012 (Nazarov A.) с IP 45.132.74.19 (Москва). Аккаунт заблокирован автоматически.",
    status: "active",
  },
  {
    id: "SEC-002",
    timestamp: d(0, 8, 30, 0),
    severity: "warning",
    title: "Вход с нового устройства",
    description: "Пользователь Каримов Джамшид (USR-001) вошёл с нового устройства: iPhone, Safari 17.5, IP 195.158.31.42 (Ташкент).",
    status: "resolved",
    resolvedAt: d(0, 9, 0, 0),
    resolvedBy: "Каримов Джамшид",
  },
  {
    id: "SEC-003",
    timestamp: d(1, 2, 45, 0),
    severity: "critical",
    title: "Подозрительный IP-адрес",
    description: "Попытка входа с IP 45.132.74.19 (Москва, RU) — адрес не из белого списка. Пользователь: USR-012. Вход заблокирован.",
    status: "active",
  },
  {
    id: "SEC-004",
    timestamp: d(1, 14, 0, 0),
    severity: "warning",
    title: "Массовый экспорт данных",
    description: "Пользователь Рахимова Дилноза (USR-002) экспортировала 312 записей заявок за один запрос. Превышен порог в 200 записей.",
    status: "resolved",
    resolvedAt: d(1, 14, 30, 0),
    resolvedBy: "Каримов Джамшид",
  },
  {
    id: "SEC-005",
    timestamp: d(2, 10, 0, 0),
    severity: "info",
    title: "Изменение критических настроек",
    description: "Пользователь Каримов Джамшид (USR-001) изменил политику паролей: минимальная длина 8 → 12, добавлена принудительная 2FA для Admin.",
    status: "resolved",
    resolvedAt: d(2, 10, 5, 0),
    resolvedBy: "Каримов Джамшид",
  },
  {
    id: "SEC-006",
    timestamp: d(3, 1, 0, 0),
    severity: "critical",
    title: "Brute-force атака обнаружена",
    description: "12 попыток входа с различными логинами с IP 91.108.56.78 в течение 2 минут. IP заблокирован на 24 часа.",
    status: "resolved",
    resolvedAt: d(3, 9, 0, 0),
    resolvedBy: "Система (авто)",
  },
  {
    id: "SEC-007",
    timestamp: d(4, 11, 0, 0),
    severity: "warning",
    title: "Отключение 2FA",
    description: "Пользователь Абдуллаев Бекзод (USR-003) отключил двухфакторную аутентификацию для пользователя USR-008.",
    status: "active",
  },
  {
    id: "SEC-008",
    timestamp: d(5, 8, 0, 0),
    severity: "info",
    title: "Ротация API-ключа",
    description: "API-ключ партнёра Multicard (P-005) был перевыпущен пользователем Каримов Джамшид (USR-001). Старый ключ деактивирован.",
    status: "resolved",
    resolvedAt: d(5, 8, 5, 0),
    resolvedBy: "Каримов Джамшид",
  },
  {
    id: "SEC-009",
    timestamp: d(6, 15, 0, 0),
    severity: "warning",
    title: "Сессия из необычного местоположения",
    description: "Пользователь Каримов Джамшид (USR-001) установил сессию с IP 45.132.74.19 (Москва, RU). Обычная геолокация: Ташкент, UZ.",
    status: "resolved",
    resolvedAt: d(6, 15, 10, 0),
    resolvedBy: "Каримов Джамшид",
  },
  {
    id: "SEC-010",
    timestamp: d(7, 4, 0, 0),
    severity: "critical",
    title: "Массовое удаление записей",
    description: "Обнаружена попытка удаления 15 записей клиентов за 1 минуту. Операция заблокирована. Пользователь: USR-003 (Абдуллаев Бекзод).",
    status: "active",
  },
];

// ── Alert Rules (5) ────────────────────────────────────────────────────

export const ALERT_RULES: AlertRule[] = [
  {
    id: "RULE-001",
    trigger: "Неудачные попытки входа",
    threshold: 5,
    unit: "попыток",
    windowMinutes: 10,
    recipients: ["USR-001", "USR-002"],
    enabled: true,
  },
  {
    id: "RULE-002",
    trigger: "Массовое удаление",
    threshold: 10,
    unit: "записей",
    windowMinutes: 5,
    recipients: ["USR-001"],
    enabled: true,
  },
  {
    id: "RULE-003",
    trigger: "Подозрительный IP",
    threshold: 1,
    unit: "попытка",
    windowMinutes: 1,
    recipients: ["USR-001", "USR-002", "USR-003"],
    enabled: true,
  },
  {
    id: "RULE-004",
    trigger: "Массовый экспорт",
    threshold: 200,
    unit: "записей",
    windowMinutes: 60,
    recipients: ["USR-001"],
    enabled: false,
  },
  {
    id: "RULE-005",
    trigger: "Изменение критических настроек",
    threshold: 1,
    unit: "изменение",
    windowMinutes: 1,
    recipients: ["USR-001", "USR-002"],
    enabled: true,
  },
];
